### ISSUE TITLE
plugindir broken on windows

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#64] opened 2020-01-21 11:05 UTC
Trying out hiera 0.3 and getting an error with plugins

```
version: 5
defaults:
  plugindir: C:\Temp\hiera\plugins
hierarchy:
  - name: one
    data_hash: terraform_backend
    options:
      backend: local
      config:
        path: C:\Temp\hiera\one.tfstate
```

```
lookup.exe test
Error: unable to start plugin /C:/Temp/hiera/plugins/terraform_backend.exe: exec: "/C:/Temp/hiera/plugins/terraform_backend.exe": file does not exist
```

Looks like `(dgo.Loader).AbsoluteName()` is returning the path with `/` prefixed

**Comment by thallgren** [comment] 2020-01-21 15:24
The loader AbsoluteName should return a name that reflects a loader hierarchy (which isn't necessary a path) so that part is correct. The problem is that a Windows path isn't directly translatable to a slash separated path. I'll try and fix that.

**Comment by thallgren** [comment] 2020-01-21 15:46
There's a pending PR on hiera_terraform https://github.com/lyraproj/hiera_terraform/pull/5 which must be updated once #65 is merged and a new tag has been set.
@hbuckle I can't add  you as a reviewer on hiera_terraform at the moment. I invited you to be a contributor to resolve that.

**Closed** 2020-01-22 10:30 UTC
