### ISSUE TITLE
dgo local references

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#74] opened 2020-03-02 10:53 UTC
I think I'm seeing something similar to [this](https://github.com/lyraproj/hiera/pull/50/commits/af5a9532c7433f9cefba96ae47ca7028a55e3ab4) - for some lookups I get back `__ref: 26` or similar on the first try, but retrying the lookup returns the correct value. I can't figure out exactly what's triggering it, but I think it's only when using `strict_alias`. Also passing `--dialect pcore` seems to make it work first time.

**Comment by thallgren** [comment] 2020-03-02 12:23
@hbuckle I think I know where the problem is but I'd like to know two things to be certain:
1. What version are you using?
2. Do you see the same thing if you use `--render-as json`?

**Comment by hbuckle** [comment] 2020-03-02 13:00
@thallgren 

1. Using the latest tagged version 0.3.6, and hiera_terraform built from master

2. `--render-as json` exhibits the same behvaiour - `"{\"__ref\":26}"`

**Comment by thallgren** [comment] 2020-03-03 12:05
Inadvertently closed by merge of #75 (which doesn't fix the problem).

**Closed** 2020-03-03 12:05 UTC
